### PR TITLE
WIP:csharp should wrap python test too

### PR DESCRIPTION
**Pull request by Laeeth**
Doesn't make sense to have different tests/examples for csharp and python!  This won't work right now because of bugs in csharp autowrap.  Had we used the same test/example we would have caught bugs earlier.

### CODE REVIEW

**Comment by atilaneves** [comment]
This makes sense. I'll work on the branch and merge it once the issues are fixed.

**Comment by atilaneves** [comment]
Closed in favour of #99

**Comment by Laeeth** [comment]
Atila #99 doesn't wrap Excel too.  I would like to have some tests that work with everything, which means Excel initially but in time maybe SIL and more.

**Comment by atilaneves** [comment]
@Laeeth Excel is handled by excel-d. All autowrap does there is change the API. This PR's title is about C#, it doesn't build and won't advance getting the work done to unify the API for all languages and/or test that Excel wrapping works with the examples. I agree the work should be done, but I don't think this PR helps the effort.

**Comment by Laeeth** [comment]
It's not particularly surprising it doesn't build when I handed it over in December and it's almost September.  It did build at the time though.  Yes, it would have been better had the title been correct but I do not see a logical connection between that and anything else because we did discuss this at the time and it's in the comment.

I'm quite familiar with how excel-d works because I wrote the first version of it, ported the headers myself manually, used Andrei allocator to replace the sdk memory pool and had very crude marshaling.  What it didn't do at all was registration of functions though Stefan had something that sort of worked.  It's much better off for you having rewritten it and I am grateful for that.  But I am quite familiar with what autowrap does and what excel - D does.

I'm used to seeing arguments phrased in more concrete terms.  Why won't it advance the work on unifying the api?  I mean if you want a single api, starting with a single set of tests is not a crazy idea.  It might not be a good idea conceivably but the way I would like to operate is that unless time is very pressing or something one doesn't start from saying I think we should not do it or by calling it a pejorative term but at least should say a few words more about why.

**Comment by atilaneves** [comment]
> I mean if you want a single api, starting with a single set of tests is not a crazy idea. 

Not at all, it's a very good idea. It's just that #99 started doing that for C# and this PR doesn't do anything for Excel apart from building the example code. I think it's a good idea to test that Excel can wrap the same things that Python can, or to state in test form, that it can't. I've opened #125 to track this.

>  Why won't it advance the work on unifying the api?

There are 3 different calls in the PR, one for each language. This is an idea of how I'd like examples/simple/source/app.d to look like once #34 is closed:

```d
import autowrap;
enum str = wrapDlang!(
    LibraryName("simple"),
    Modules(
        Module("prefix"),
        Module("adder"),
        Module("wrap_all", Yes.alwaysExport)
    ),
);
```

It'll look different because it'll have to cater to all different environments, but I want `import autowrap` to "just work", with the selection of which language happening probably in dub.sdl.

**Comment by Laeeth** [comment]
Yes there are 3 different calls in the PR.  Imagine I had actually unified them.  My best prediction is that you might say it's too big a PR.

So I think that its correct to say that whilst it doesn't unify the API it does advance the work because its better not to have different tests for each platform as we do currently.

**Comment by atilaneves** [comment]
> its better not to have different tests for each platform as we do currently.

Yes, and I'm currently thinking of how to make it better. It'll probably involve making the Python tests polymorphic with respect to platform so that we "write once, test everywhere".

I'm reopening and merging in the meanwhile.

**Pull request merged**
